### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by tuanha2000vn** [muslimtv/flutter_playout#24]
```
E/PlayerLayout(30902): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/PlayerLayout(30902): 	at tv.mta.flutter_playout.video.PlayerLayout$2.run(PlayerLayout.java:460)
E/PlayerLayout(30902): 	at android.os.Handler.handleCallback(Handler.java:883)
E/PlayerLayout(30902): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/PlayerLayout(30902): 	at android.os.Looper.loop(Looper.java:214)
E/PlayerLayout(30902): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/PlayerLayout(30902): 	at java.lang.reflect.Method.invoke(Native Method)
E/PlayerLayout(30902): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/PlayerLayout(30902): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
D/PlayerLayout(30902): onTime: [time=0]
E/PlayerLayout(30902): onTime: 
```

Thank for the great repo, how can I fix this? It's not crashing but it look ugly on log :D

**Comment by thanhkhanhcntt** [comment]
It's only anroid, I face same problem
```
E/PlayerLayout(10826): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/PlayerLayout(10826): 	at tv.mta.flutter_playout.video.PlayerLayout$2.run(PlayerLayout.java:453)
E/PlayerLayout(10826): 	at android.os.Handler.handleCallback(Handler.java:883)
E/PlayerLayout(10826): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/PlayerLayout(10826): 	at android.os.Looper.loop(Looper.java:237)
E/PlayerLayout(10826): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/PlayerLayout(10826): 	at java.lang.reflect.Method.invoke(Native Method)
E/PlayerLayout(10826): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/PlayerLayout(10826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
D/PlayerLayout(10826): onTime: [time=59]
E/PlayerLayout(10826): onTime: 
E/PlayerLayout(10826): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/PlayerLayout(10826): 	at tv.mta.flutter_playout.video.PlayerLayout$2.run(PlayerLayout.java:453)
E/PlayerLayout(10826): 	at android.os.Handler.handleCallback(Handler.java:883)
E/PlayerLayout(10826): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/PlayerLayout(10826): 	at android.os.Looper.loop(Looper.java:237)
E/PlayerLayout(10826): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/PlayerLayout(10826): 	at java.lang.reflect.Method.invoke(Native Method)
E/PlayerLayout(10826): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/PlayerLayout(10826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
D/BufferPoolAccessor(10826): bufferpool2 0x7c584df620 : 6(49152 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 27/10875 (fetch/transfer)
```

**Comment by SimonPeter1909** [comment]
me too
