### ISSUE TITLE
App Crash on Video Play.

### ISSUE THREAD

**Issue by devopsflutter** [muslimtv/flutter_playout#88]
E/PlayerLayout(31847): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/PlayerLayout(31847): 	at tv.mta.flutter_playout.video.PlayerLayout$PlayerAnalyticsEventsListener.onSeekProcessed(PlayerLayout.java:756)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.lambda$onSeekProcessed$53(DefaultAnalyticsCollector.java:721)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.analytics.-$$Lambda$DefaultAnalyticsCollector$Vh8fhUs3zupZ8HUCvzE4ugOkc4g.invoke(Unknown Source:4)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:226)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.sendEvent(DefaultAnalyticsCollector.java:894)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.onSeekProcessed(DefaultAnalyticsCollector.java:720)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.-$$Lambda$WQ-kXTH-nRF1eRuXjCVHuBppSqQ.invoke(Unknown Source:2)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1947)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:820)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:887)
E/PlayerLayout(31847): 	at com.google.android.exoplayer2.BasePlayer.seekTo(BasePlayer.java:131)
E/PlayerLayout(31847): 	at tv.mta.flutter_playout.video.PlayerLayout.initPlayer(PlayerLayout.java:245)
E/PlayerLayout(31847): 	at tv.mta.flutter_playout.video.PlayerLayout.<init>(PlayerLayout.java:199)
E/PlayerLayout(31847): 	at tv.mta.flutter_playout.video.PlayerView.<init>(PlayerView.java:23)
E/PlayerLayout(31847): 	at tv.mta.flutter_playout.video.PlayerViewFactory.create(PlayerViewFactory.java:48)
E/PlayerLayout(31847): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:185)
E/PlayerLayout(31847): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:708)
E/PlayerLayout(31847): 	at android.app.Dialog.show(Dialog.java:422)
E/PlayerLayout(31847): 	at android.app.Presentation.show(Presentation.java:285)
E/PlayerLayout(31847): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/PlayerLayout(31847): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/PlayerLayout(31847): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:214)
E/PlayerLayout(31847): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/PlayerLayout(31847): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/PlayerLayout(31847): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/PlayerLayout(31847): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/PlayerLayout(31847): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/PlayerLayout(31847): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/PlayerLayout(31847): 	at android.os.Handler.handleCallback(Handler.java:938)
E/PlayerLayout(31847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/PlayerLayout(31847): 	at android.os.Looper.loop(Looper.java:246)
E/PlayerLayout(31847): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/PlayerLayout(31847): 	at java.lang.reflect.Method.invoke(Native Method)
E/PlayerLayout(31847): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/PlayerLayout(31847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(31847): FATAL EXCEPTION: main
E/AndroidRuntime(31847): Process: com.anandsolutions.godlybank, PID: 31847
E/AndroidRuntime(31847): java.lang.NoSuchMethodError: No virtual method createMediaSource(Landroid/net/Uri;)Lcom/google/android/exoplayer2/source/ProgressiveMediaSource; in class Lcom/google/android/exoplayer2/source/ProgressiveMediaSource$Factory; or its super classes (declaration of 'com.google.android.exoplayer2.source.ProgressiveMediaSource$Factory' appears in /data/app/~~9DtsSaS_vCO2BADHwZWJCg==/com.anandsolutions.godlybank-E2fTqmQu0nhID7tubMLC0A==/base.apk)
E/AndroidRuntime(31847): 	at tv.mta.flutter_playout.video.PlayerLayout.updateMediaSource(PlayerLayout.java:514)
E/AndroidRuntime(31847): 	at tv.mta.flutter_playout.video.PlayerLayout.initPlayer(PlayerLayout.java:259)
E/AndroidRuntime(31847): 	at tv.mta.flutter_playout.video.PlayerLayout.<init>(PlayerLayout.java:199)
E/AndroidRuntime(31847): 	at tv.mta.flutter_playout.video.PlayerView.<init>(PlayerView.java:23)
E/AndroidRuntime(31847): 	at tv.mta.flutter_playout.video.PlayerViewFactory.create(PlayerViewFactory.java:48)
E/AndroidRuntime(31847): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:185)
E/AndroidRuntime(31847): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:708)
E/AndroidRuntime(31847): 	at android.app.Dialog.show(Dialog.java:422)
E/AndroidRuntime(31847): 	at android.app.Presentation.show(Presentation.java:285)
E/AndroidRuntime(31847): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime(31847): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime(31847): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:214)
E/AndroidRuntime(31847): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/AndroidRuntime(31847): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(31847): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(31847): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/AndroidRuntime(31847): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/AndroidRuntime(31847): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/AndroidRuntime(31847): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(31847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31847): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(31847): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/AndroidRuntime(31847): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31847): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(31847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process (31847): Sending signal. PID: 31847 SIG: 9
Lost connection to device.

**Comment by KhuramKhalid** [comment]
Which version are you using?

**Comment by devopsflutter** [comment]
flutter_playout: ^2.0.1

**Comment by devopsflutter** [comment]
> Which version are you using?

flutter_playout: ^2.0.1
